---
title: Influence of School Closure on COVID-19 Contaminations in Ireland and Repercussions across Age Groups
author:
  - name: Edgar Morgenroth
    email: edgar.morgenroth@dcu.ie
    affiliation: Dublin City University
    footnote: 1
  - name: Damien Dupré
    email: damien.dupre@dcu.ie
    affiliation: Dublin City University
    footnote: 2
address:
  - code: Dublin City University
    address: 	Glasnevin, Dublin 9, Ireland
footnote:
  - code: 1
    text: "Corresponding Author"
  - code: 2
    text: "Equal contribution"
abstract: |
  TBD

journal: "TBD"
date: "`r Sys.Date()`"

csl: ["csl/elsevier-harvard.csl"]
bibliography: ["bib/reference_list.bib"]

#linenumbers: true
#numbersections: true

output: rticles::elsevier_article
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = here::here("output"),
      output_file = glue::glue("{xfun::sans_ext(input)}_{Sys.Date()}.pdf"),
      envir = globalenv()
    )
  })
---

Introduction
==========================

Since the onset of Covid-19, contradicting messages are circulating about the spread of the virus in schools. Sometimes presented as a safe environment [@falk2021covid; @walger2020children], at other times designed as an aggravating factor of the pandemic [@lopez2020transmission; @meuris2021transmission], child care facilities and schools have been closed multiple times in most countries to protect the public health. However, the efficacy of school closure is still unknown and little is know about how Covid-19 Cases spread across age cohort and especially from the younger cohort being at school to older cohorts including parents, grand parents and relatives. Some evidence show that school is an influential environment where the virus is likely to spread. Once contaminated at school, a common spread believe is that the children and teenagers will then contaminate their parents. Therefore, among the political actions to stop the spread of Covid-19, the closure of primary and secondary schools was widely adopted worldwide. This research aims to investigate 1) the effect of school closure on the evolution of Covid-19 cases and 2) the temporal relationship between the rise of cases in children and teenagers with the rise of cases of older age group.

## Influence of School Closure

One of the strongest assumption of government actions is that by reducing social contact will reduce the spread of the virus. Therefore, it is legitimate to believe that by closing schools, a reduction of the contaminations would be observed in the younger age groups. However, the efficiency of school closure on the reduction of Covid-19 cases is still questioned. While some research have observed that school closures contribute to limit or to reduce the growth rate of confirmed cases after implementation [@yoshiyuki2020effects; @stage2021shut], other did not observe a change in the evolution of Covid-19 cases [@iwata2020school; @chang2020modelling]. For instance, a controlled comparison between similar localities in Japan with schools closed and school open did not revealed any evidence that school closures reduced the spread of Covid-19 [@fukumoto2021no]. If the school closure had a real impact on the evolution of confirmed Covid-19 cases, it should be possible to observe a decrease or a least an inflection in the trend of its evolution among younger age groups.

## Causal Relationship Between Age Groups

A second implicit believe regarding the effect of school closure on the spread of Covid-19 is that school not only has an effect on to the spread of the virus in children and teenagers but also has a knock-on effect on the spread of the virus in older age groups also called Secondary Attack Rate (SAR). The contaminated children and teenagers would bring the virus back at home and, then, they will contaminate their parents and relatives. For example, a research investigating the contamination in the household network not only revealed an exceptional high rate of secondary contamination but also that these contamination happened when the school were closed [@sorianoarandes2021household]. 

Despite being reported in several clinical and epidemiological studies [@zhendong2020clinical; @siebach2021childhood], multiple research have shown that the SAR from children to household members was, in fact, lower than expected [@kim2021role; @ludvigsson2020children; @vanderhoek2020role; @heavey2020evidence]. However, the SAR of children and teenagers to the household member is likely to be age-dependent, with difference between infants, primary and secondary school children, and college students [@grasleguen2021reopening]. If a secondary transmission from children and teenagers to household member has a significant influence, then a temporal causality relationship between their evolution should be observed.

Method
============

## Observations

The data were collected from the official daily publication of Covid-19 cases by the Irish Department of Health. They include the amount of daily cases for 10 age groups from March 4th, 2020 to January 1st, 2022. For each day during this period, school closure either due to a government decision or a public holiday is determined.

## Data Pre-processing

A 7-day rolling average of the day-by-by change in Covid-19 cases reported (i.e., lag 1) is used to evaluate the efficiency of school closures. This rolling average approximate the real day-by-by change in Covid-19 cases reported which can be artificially increased or decreased due to days under- or over-reporting cases such as weekend or bank holidays for example.

## Data Analysis

Four periods of school closure longer that 14 days have been identified. These four periods are used to fit a Generalised Additive Model (or GAM) using the R package mgcv [@wood2017generalized] in order to test the hypothesis of a significant change in the evolution of cases among age groups from 1 to 4, from 5 to 14, and from 15 to 24.

By estimating the degree of smoothness of a Bayesian spline smoothing using restricted maximum likelihood estimation [@wood2011fast], GAMs allow the identification of dynamic patterns underlying the day-by-day changes in Covid-19 cases reported while taking into account the random effect of different age groups as follows:

\begin{align}
Y_{is} = \alpha_{i} + f(X_{s}) + a_{is} + \epsilon_{is}
\end{align}

\noindent where $i$ is an age group among the 10 age groups investigated and $s$ is the date corresponding to the day-by-day change in Covid-19 cases. $Y_{is}$ represents the day-by-day change in Covid-19 cases assuming a negative binomial distribution for the fitting [@loader2006local]. The response variable $Y_{is}$ includes a specific intercept for each age group ($\alpha_{i}$). A smooth effect over time $f(X_{s})$ is applied to model (Eq 1) to predict the nonlinear evolution of day-by-day change in Covid-19 cases. This smooth effect $f(X_{s})$ is built up in basic components, called the basis functions $b_{j}(X_{s})$, such that:

\begin{align}
f(X_{s})=\sum_{j=1}^{k}\beta_{j}\times b_{j}(X_{s})
\end{align}

\noindent where the regression parameters $\beta_{j}$ are estimated by penalized likelihood maximization.

The model also includes the random effects term $a_{is}= Zb_{i}$ where $Z$ is a random effects matrix and $b_{i}$ is a vector of random effects described by $b_{i} \sim N(0, D)$. In this, $D$ represents a covariance matrix. The error term $\epsilon_{is}$ is assumed to be normally and independently distributed $\epsilon_{is} \sim N(0, \sigma^2)$.

Contrary to Granger Causality, Transfer Entropy is robust to non-stationary time series [@silini2021fast]. The Transfer Entropy analysis of younger age groups daily changes in Covid-19 cases on older age groups is done using the R package RTransferEntropy [@behrendt2019rtransferentropy].

Results
===================

Discussion
===================

Knowledge about the transmission of the virus significantly improved with the amount of studies performed, especially in the case of how the virus behaves with children. From the early analyses showing that the virus was instantness in children [@li2020role], the results has changed to more nuanced position which states that the spread of the virus in children is moderate.

Conclusion
===================

References {#references .unnumbered}
==========
